### ISSUE TITLE
Don't show new things by default

### ISSUE THREAD

**Issue by ouuan** [anmol098/waka-readme-stats#12]
It is fine if something we want is not shown, but it could be bad if something we don't want to share is displayed. So I think new things shouldn't be shown by default. 64bb35f86d325a0b21ce9b1fe5f39af4a6c0e122 is an example of a new thing is shown by default.

And it is better to have "v1", "v2" branches in case of breaking changes. If you have a v1 branch, then you can show some new things by default in v2, or change the default settings in other ways you want.

**Comment by anmol098** [comment]
You have a valid point but we are constantly developing and adding new metrics to the project and if we disable everything by default then there's no point to develop new things as the users currently using this GitHub action will not get to know the new features added.

That's why all features are enabled by default if you don't want stats to display you can forcefully disable the stats.

**Comment by ouuan** [comment]
> if you don't want stats to display you can forcefully disable the stats

I can't do that in time if new things are enabled by default.

As for now, I've forked this repo and I'm using it in my profile.

**Comment by ouuan** [comment]
Or you can have a new setting "enable features by default" with a default value "true", and other options have three states "on", "off" and "default" with default values "default".
