### ISSUE TITLE
bar_graph.png is wrong

### ISSUE THREAD

**Issue by Arondight** [anmol098/waka-readme-stats#245]
**Describe the bug**
| date | pic |
| --- | --- |
| Nov 26, 2021 | [link](https://github.com/Arondight/Arondight/blob/b1e624b78a71505900c64815b56db564b66c6092/charts/bar_graph.png) |
| Dec 6, 2021 | [link](https://github.com/Arondight/Arondight/blob/0e05d29908335e704b8ce491caf5c75ec7aafe67/charts/bar_graph.png) |

Obviously this is wrong, and **why is there a negative 5000**?

**To Reproduce**

**Expected behavior**

**Github repository link**
https://github.com/Arondight/Arondight

**Additional context**

**Comment by Arondight** [comment]
I found this function is unstable, and the data it obtains may be quite different (and wrong)

**Comment by LukeSamkharadze** [comment]
Same issue

![image](https://user-images.githubusercontent.com/31849767/148212650-2d4fd7e4-a400-4517-bd44-b593cad730d6.png)

**Comment by pseusys** [comment]
Don't think that's an issue - I had one of those spikes recently, and it was caused by a repo I accidentally committed dependencies folder in.
Internally this graph is built with data provided directly by GitHub, so maybe your stats, collected by the site are just not very accurate. Maybe you should search for some unusually big files or heavy repos?

**Comment by Arondight** [comment]
https://github.com/Arondight/Arondight/blob/5b2924283a9f251d881d507e6c7459a97549860a/charts/bar_graph.png

it is ok now and close this issue
