### ISSUE TITLE
Add||tzmanish

### ISSUE THREAD

**Issue by tzmanish** [anmol098/waka-readme-stats#32]
**Github Profile Link**
https://github.com/tzmanish

**Your Name**
tz.man

**Comment by anmol098** [comment]
@tzmanish i could not add your name because you haven't setup the action workflow properly.
please also add the GitHub personal access token with repo and user permission to the workflow file please read the documentation for more info
https://github.com/anmol098/waka-readme-stats#profile-repository

**Comment by tzmanish** [comment]
Is it safe to add my personal access token?

**Comment by anmol098** [comment]
@tzmanish it is safe to add the token... The token is added to the secret of the repository and is used to get only the data we require and the code is open source you can check that also.

**Comment by tzmanish** [comment]
> The token is added to the secret of the repository

Pardon me for my lack of knowledge, but does that mean, you can't see or use my tocken and it can only be used by the script?

**Comment by anmol098** [comment]
Yes no one can see your token except you.... And the script will be able to use that during runtime

**Comment by tzmanish** [comment]
Thanks a lot for clearing everything out @anmol098

**Comment by tzmanish** [comment]
It's done. Now you can add my name.
